CREATE DATABASE IF NOT EXISTS techmart_db;
USE techmart_db;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    city VARCHAR(50),
    phone VARCHAR(15)
);

CREATE TABLE employees (
    employee_id INT PRIMARY KEY,
    employee_name VARCHAR(100) NOT NULL,
    department VARCHAR(50),
    manager_id INT,
    CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id)
        REFERENCES employees(employee_id)
);

CREATE TABLE categories (
    category_id INT PRIMARY KEY,
    category_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category_id INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    brand VARCHAR(50),
    stock_quantity INT,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    employee_id INT NOT NULL,
    order_date DATE NOT NULL,
    order_status VARCHAR(20) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),
    CONSTRAINT fk_order_employee FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id)
);

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_item_order FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    CONSTRAINT fk_item_product FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);
select * from employees;

-- Q1 - Display the names and cities of all customers from Hyderabad.
select customer_name,city from customers where city='hyderabad';

-- Q2 - Display each order along with the customer name, order date, and order status.
select o.order_id,c.customer_id,c.customer_name,o.order_status,o.order_date from orders o inner join customers c on o.customer_id=c.customer_id;

-- Q3 - Find all customers who have placed at least one order.
select distinct c.customer_name, c.customer_id  from customers c inner join orders o on c.customer_id=o.customer_id; 

-- Q4 - Display the customer name, order ID, and payment method for orders paid using UPI or Credit Card.
select c.customer_name, c.customer_id ,o.order_id,o.payment_method from customers c inner join orders o on c.customer_id=o.customer_id 
where o.payment_method in ('UPI','CREDIT CARD'); 

-- Q5 - Display all products whose price is between ₹5,000 and ₹20,000, sorted from highest to lowest price.
select * from products where price between 5000 and 20000 order by price desc; 

-- Q6 - Find the number of orders placed by each customer.
SELECT c.customer_id,c.customer_name,COUNT(o.order_id) AS number_of_orders
FROM customers c INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

-- Q7 - Display all customers, including customers who have never placed an order.
select c.customer_name, c.customer_id ,o.order_id from customers c left join orders o on c.customer_id=o.customer_id;
 
-- Q8 - Find the customers who have never placed an order.
select c.customer_name, c.customer_id ,o.order_id from customers c left join orders o on c.customer_id=o.customer_id where o.order_id is null; 

-- Q9 - Display each order with the customer name and employee name who handled it.
select c.customer_name,o.employee_id,o.order_id,e.employee_name from orders o inner join customers c on c.customer_id=o.customer_id 
inner join employees e on e.employee_id=o.employee_id;

-- Q10 - Display the product name, category name, brand, and price for every product.
select c.category_name,c.category_id,p.product_name,p.price,p.brand from products p inner join categories c on p.category_id=c.category_id;

-- Q11 - Find the total quantity sold for each product.
select p.product_name,sum(oi.quantity) as total_quantity from order_items oi inner join products p on p.product_id=oi.product_id group by product_name;

-- Q12 - Find the total revenue generated by each product using: quantity × unit_price
select p.product_name,sum(oi.quantity*oi.unit_price) as total_revenue from order_items oi inner join
 products p on oi.product_id=p.product_id group by p.product_name;
 
-- Q13 - Display the top 5 products by total revenue.
select p.product_name,sum(oi.quantity*oi.unit_price) as total_revenue from order_items oi inner join
 products p on oi.product_id=p.product_id group by p.product_name order by total_revenue desc limit 5;
 
-- Q14 - Find the total amount spent by each customer.
select c.customer_name,c.customer_id,sum(oi.quantity*oi.unit_price) as total_amount from customers c inner join orders o on c.customer_id=o.customer_id 
inner join order_items oi on o.order_id=oi.order_id group by c.customer_name,c.customer_id;

-- Q15 - Display the top 5 customers by total spending.
select c.customer_name,c.customer_id,sum(oi.quantity*oi.unit_price) as total_spending from customers c inner join orders o on c.customer_id=o.customer_id
 inner join order_items oi on o.order_id=oi.order_id group by c.customer_name,c.customer_id order by total_spending desc limit 5;
 
-- Q16 - Find customers whose total spending is greater than ₹30,000.
select c.customer_name,c.customer_id,sum(oi.quantity*oi.unit_price) as total_spending from customers c inner join orders o on c.customer_id=o.customer_id 
inner join order_items oi on o.order_id=oi.order_id group by c.customer_name,c.customer_id having total_spending>30000;

-- Q17 - Find the total revenue generated by each product category.
select c.category_name,p.category_id,sum(oi.quantity*oi.unit_price) as total_revenue from order_items oi 
inner join products p on oi.product_id=p.product_id inner join categories c on c.category_id=p.category_id group by c.category_name,p.category_id;

-- Q18 - Display categories whose total revenue is greater than ₹50,000, sorted by revenue from highest to lowest.
select c.category_name,p.category_id,sum(oi.quantity*oi.unit_price) as total_revenue from order_items oi 
inner join products p on oi.product_id=p.product_id inner join categories c on c.category_id=p.category_id group by c.category_name,p.category_id 
having total_revenue>50000 order by total_revenue desc ;

-- Q19 - Find the number of orders handled by each employee.
select count(order_id) as number_of_orders,e.employee_id,e.employee_name from orders o inner join employees e on o.employee_id=e.employee_id
 group by e.employee_name,e.employee_id;
 
-- Q20 - Display employees who have handled more than 3 orders.
select count(order_id) as number_of_orders,e.employee_id,e.employee_name from orders o inner join employees e on o.employee_id=e.employee_id
 group by e.employee_name,e.employee_id having number_of_orders>3;
 
-- Q21 - Find the average order value for each customer.
select c.customer_name,c.customer_id,sum(oi.quantity*oi.unit_price) /count(distinct o.order_id) as avg_order_value from order_items oi inner join orders o 
on oi.order_id=o.order_id inner join customers c on c.customer_id=o.customer_id group by c.customer_name,c.customer_id;

-- Q22 - Display customers whose average order value is greater than ₹15,000.
select c.customer_name,c.customer_id,sum(oi.quantity*oi.unit_price) /count(distinct o.order_id) as avg_order_value from order_items oi 
inner join orders o on oi.order_id=o.order_id
inner join customers c on c.customer_id=o.customer_id group by c.customer_name,c.customer_id having avg_order_value >15000 ;

-- Q23 - Find the number of orders for each order status.
select o.order_status,count(o.order_id) as number_of_orders from orders o group by o.order_status;

-- Q24 - Find the total revenue generated from Delivered orders only, grouped by category.
select c.category_name,sum(oi.quantity*oi.unit_price) as total_revenue from order_items oi inner join orders o on oi.order_id=o.order_id inner join 
products p on oi.product_id=p.product_id inner join categories c on c.category_id=p.category_id 
  where  o.order_status='delivered' group by c.category_name;
  
-- Q25 - Categorize products based on price: Below ₹5,000 → Budget ₹5,000–₹15,000 → Standard Above ₹15,000 → Premium
select product_name,case when p.price <5000 then 'budget' 
when p.price between 5000 and 15000 then 'standard'
else 'premium'
end as categorised_products from products p;

-- Q27 - Count how many products belong to each price category.
select count(*),case when p.price <5000 then 'budget' 
when p.price between 5000 and 15000 then 'standard'
else 'premium'
end as price_category from products p group by case when p.price <5000 then 'budget' 
when p.price between 5000 and 15000 then 'standard'
else 'premium'
end;

-- Q28 -Display each employee along with their manager's name.
select e.employee_id,e.employee_name,m.employee_name as manager_name,m.manager_id from employees e join employees m on m.employee_id=e.manager_id;

-- Q29 - Display all employees, including those who do not have a manager.
select e.employee_id,e.employee_name,m.employee_name,m.manager_id from employees e left join employees m on m.employee_id=e.manager_id; 

-- Q30 -Find the number of customers in each city who have placed orders, and display only cities having more than 2 customers.
select c.city,count(distinct c.customer_id) as number_of_customers from customers c 
inner join orders o on c.customer_id=o.customer_id group by c.city having number_of_customers>2;

-- Final Challenge Questions
-- Q31 - Find the top 3 customers by spending on Delivered orders, considering only customers whose total spending is greater than ₹20,000.
select c.customer_id,c.customer_name,sum(oi.quantity*oi.unit_price) as total_spending from order_items oi inner join orders o on oi.order_id=o.order_id 
inner join customers c on c.customer_id=o.customer_id where order_status='delivered' 
group by c.customer_name,c.customer_id having total_spending >20000 order by total_spending desc limit 3;
 
-- Q32 - Find the top 3 product categories by revenue, considering only products priced above ₹5,000.
select c.category_id,c.category_name,sum(oi.quantity*oi.unit_price) as total_revenue from products p inner join order_items oi on oi.product_id=p.product_id
 inner join categories c on c.category_id=p.category_id where p.price>5000
 group by c.category_name,c.category_id order by total_revenue desc limit 3;
 
-- Q33 - Find employees who handled more than 2 Delivered orders, along with the total revenue generated by those orders.
select e.employee_name,count(distinct o.order_id) as total_orders,sum(oi.quantity*oi.unit_price) as total_revenue from employees e
 inner join orders o on o.employee_id=e.employee_id inner join order_items oi on oi.order_id=o.order_id
 where o.order_status='delivered' group by e.employee_name having total_orders>2;
 
-- Q34 - For every customer, 
/*display:
Customer name
Number of orders
Total quantity of products purchased
Total spending
Sort by total spending descending.
*/
select c.customer_name,count(distinct o.order_id) as number_of_orders,sum(oi.quantity)as total_quantity,sum(oi.quantity*oi.unit_price) as total_spending
 from customers c left join orders o on c.customer_id=o.customer_id left join order_items oi on oi.order_id=o.order_id group by c.customer_name
order by total_spending desc;

-- Q35 -  Find the top 3 customers who:
/*
have placed more than 2 orders
have purchased products from more than one category
have total spending greater than ₹30,000
consider only Delivered orders
display customer name, order count, total spending
sort by total spending descending
*/
select c.customer_name,COUNT(DISTINCT ca.category_id) AS number_of_categories,count(distinct o.order_id) as order_count,sum(oi.quantity*oi.unit_price) as total_spending 
from customers c 
inner join orders o on c.customer_id=o.customer_id inner join order_items oi on oi.order_id=o.order_id inner join products p on oi.product_id=p.product_id
inner join categories ca on ca.category_id=p.category_id
where o.order_status='delivered' group by c.customer_name,c.customer_id
having order_count>2 and total_spending>30000 and number_of_categories>1
order by total_spending desc limit 3;

































































































