CREATE DATABASE IF NOT EXISTS airlines_db;
USE airlines_db;

CREATE TABLE flights (
    booking_id INT PRIMARY KEY,
    passenger_name VARCHAR(100) NOT NULL,
    source_city VARCHAR(50) NOT NULL,
    destination_city VARCHAR(50) NOT NULL,
    airline VARCHAR(50) NOT NULL,
    flight_class VARCHAR(20) NOT NULL,
    ticket_price DECIMAL(10,2) NOT NULL,
    passenger_age INT NOT NULL,
    flight_duration_hours DECIMAL(4,1) NOT NULL,
    baggage_kg DECIMAL(5,1) NOT NULL,
    booking_status VARCHAR(20) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    seat_number VARCHAR(10) NOT NULL
);

-- part 1 — Getting Comfortable with Aggregation

-- Q1 -  How many bookings are present in the flights table?
select count(*) as total_bookings from flights;

-- Q2 - What is the total ticket revenue generated from all bookings?
select sum(ticket_price) as total_revenue from flights;

-- Q3 - What is the average ticket price, cheapest ticket price, and most expensive ticket price?
select round(avg(ticket_price),2)as avg_ticket_price,min(ticket_price) as cheapest_ticket, max(ticket_price) as most_expensive_ticket from flights;

-- Q4 - What is the average ticket price, cheapest ticket price, and most expensive ticket price?
select count(*) as number_of_bookings,sum(ticket_price) as total_revenue,round(avg(ticket_price),2) as avg_ticket_price from flights where flight_class='business';

-- part 2 — GROUP BY 

-- Q5 -  Find the number of bookings made through each airline.
select airline,count(*) as no_of_bookings from flights group by airline;

-- Q6 - Find the total ticket revenue generated by each airline.
select airline,sum(ticket_price) as total_revenue from flights group by airline;

-- Q7 - Find the average ticket price for each airline.
select airline,round(avg(ticket_price),2) as avg_ticket_price from flights group by airline;

-- Q8 - For every airline, display: Number of bookings,Total revenue, Average ticket price, Cheapest ticket ,Most expensive ticket.
select airline, count(*) as number_of_bookings,sum(ticket_price) as total_revenue,
round(avg(ticket_price),2) as avg_ticket_price,min(ticket_price) as cheapest_ticket, max(ticket_price) as most_expensive_ticket from flights group by airline; 

-- Q9 - Find the number of bookings and total revenue generated from each source city.
select source_city,count(*) as no_of_bookings,sum(ticket_price) as total_revenue from flights group by source_city;

-- Q10 - Find the average ticket price for Economy and Business class separately.
select flight_class,round(avg(ticket_price),2) as avg_ticket_price from flights group by flight_class;

-- part 3 — WHERE + GROUP BY + HAVING
-- Q11 -  Find airlines that have more than 5 bookings, considering only bookings where the ticket price is greater than ₹5,000.
select airline,count(*) as total_bookings from flights where ticket_price >5000 group by airline having total_bookings>5;

-- Q12 - Find airlines whose total ticket revenue is greater than ₹80,000, considering only bookings where the ticket price is greater than ₹7,000.
select airline,sum(ticket_price) as total_revenue from flights where ticket_price >7000 group by airline having total_revenue>80000;

-- Q13 -  Find source cities whose average ticket price is greater than ₹10,000, considering only Business class bookings.
select source_city,avg(ticket_price) as avg_ticket_price from flights where flight_class='business' group by source_city having avg_ticket_price>10000;

-- Q14 - Find airlines that have more than 5 confirmed bookings, considering only bookings where the ticket price is greater than ₹5,000.
select airline,count(*) as total_bookings from flights where ticket_price >5000 and booking_status='confirmed' group by airline having total_bookings>5;

-- Q15 - Find airlines whose average ticket price is greater than ₹12,000, considering only passengers whose age is between 20 and 35.
select airline,avg(ticket_price) as avg_ticket_price from flights where passenger_age between 20 and 35 group by airline having avg_ticket_price>12000;

-- part 4 — HAVING + ORDER BY
-- Q16 - Find airlines that have more than 10 bookings and display them from the highest number of bookings to the lowest.
select airline,count(*) as total_bookings from flights group by airline having total_bookings>10 order by total_bookings desc;

-- Q17 - Find airlines whose total revenue is greater than ₹1,00,000 and display them from highest revenue to lowest.
select airline,sum(ticket_price) as total_revenue from flights group by airline having total_revenue >100000 order by total_revenue desc;

-- Q18 -  Find source cities with more than 10 bookings, and display them from highest number of bookings to lowest.
select source_city,count(*) as total_bookings from flights group by source_city having total_bookings>10 order by total_bookings desc;

-- part 5 - Aggregation + ORDER BY + LIMIT
-- Q19 - Which airline generated the highest total ticket revenue?
select airline,sum(ticket_price) as highest_total_ticket_revenue from flights group by airline order by highest_total_ticket_revenue desc limit 1;

-- Q20 - Display the top 3 airlines by total ticket revenue.
select airline,sum(ticket_price) as total_ticket_revenue from flights group by airline order by total_ticket_revenue desc limit 3;

-- Q21 -  Display the top 3 airlines by average ticket price.
select airline,avg(ticket_price) as average_ticket_price from flights group by airline order by average_ticket_price desc limit 3;

-- Q22 - Display the top 3 source cities by number of bookings.
select source_city,count(*) as no_of_bookings from flights group by source_city order by no_of_bookings desc limit 3;

-- Part 6 — CASE
-- Q23 - Categorize every passenger based on age: 18–25 → Young 26–35 → Adult Above 35 → Senior
select passenger_name,passenger_age, case
when passenger_age between 18 and 25 then 'young'
when passenger_age between 26 and 35 then 'adult'
else 'senior'
end as age_category from flights;

-- Q24 - Categorize every booking based on ticket price: Below ₹7,000 → Budget ₹7,000–₹15,000 → Standard Above ₹15,000 → Premium
-- Display the passenger name, ticket price, and ticket category.
select passenger_name,ticket_price,case
when ticket_price <7000 then 'budget'
when ticket_price between 7000 and 15000 then 'standard'
else 'premium'
end as ticket_category from flights;

-- Q25 - Categorize flights based on duration: Below 3 hours → Short 3–5 hours → Medium Above 5 hours → Long
-- Display the passenger name, flight duration, and duration category.
select passenger_name,flight_duration_hours,case
when flight_duration_hours <3 then 'short'
when flight_duration_hours between 3 and 5  then 'medium'
else 'long'
end as duration_category from flights;

-- Part 7 — CASE + GROUP BY + Aggregation
-- Q26 - Find the number of bookings in each ticket-price category: Budget / Standard / Premium
select count(*) as no_of_bookings ,case 
when ticket_price <7000 then 'budget'
when ticket_price between 7000 and 15000 then 'standard'
else 'premium'
end as ticket_price_category from flights group by case 
when ticket_price <7000 then 'budget'
when ticket_price between 7000 and 15000 then 'standard'
else 'premium'
end;

-- Q27 - Find the total revenue generated by each ticket-price category.
select sum(ticket_price) as total_revenue,case 
when ticket_price <7000 then 'budget'
when ticket_price between 7000 and 15000 then 'standard'
else 'premium'
end as ticket_price_category from flights group by case 
when ticket_price <7000 then 'budget'
when ticket_price between 7000 and 15000 then 'standard'
else 'premium'
end;
 
-- Q28 - Find the number of passengers in each age category: Young / Adult / Senior
select count(*) as no_of_passengers , case
when passenger_age between 18 and 25 then 'young'
when passenger_age between 26 and 35 then 'adult'
else 'senior'
end as age_category from flights group by case
when passenger_age between 18 and 25 then 'young'
when passenger_age between 26 and 35 then 'adult'
else 'senior'
end;

-- Part 8 — Final Mixed Challenges
-- Q29 - Find airlines that:
/* Have more than 5 confirmed bookings
Considering only bookings with ticket prices between ₹5,000 and ₹20,000
Have an average ticket price greater than ₹10,000
Display:
Airline
Number of bookings
Average ticket price
Total revenue
Sort the result by total revenue from highest to lowest.
*/
select airline,count(*) as number_of_booking,sum(ticket_price) as total_revenue, avg(ticket_price) as averge_ticket_price from flights 
where ticket_price between 5000 and 20000 and booking_status='confirmed' group by airline having averge_ticket_price>10000 and number_of_booking>5
 order by total_revenue desc;
 
-- Q30 - FINAL CHALLENGE
/* Management wants to identify the top-performing airlines.
Find airlines that:
Have more than 10 bookings
Considering only passengers older than 20
Have an average ticket price greater than ₹10,000
Have a total revenue greater than ₹1,00,000
Display:
Airline
Number of bookings
Average ticket price
Total revenue
Sort the airlines by total revenue from highest to lowest and display only the top 3.
*/
select airline,count(*) as number_of_booking,sum(ticket_price) as total_revenue, avg(ticket_price) as averge_ticket_price from flights 
where passenger_age >20 group by airline having averge_ticket_price>10000 and number_of_booking>10 and total_revenue>100000
 order by total_revenue desc limit 3;